name: Publish

on:
    push:
        tags:
            - '*'
jobs:
    release:
        name: Create new release
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Build Changelog
              id: github_release
              uses: mikepenz/release-changelog-builder-action@v4
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                                  
            - name: copy file
              uses: canastro/copy-file-action@master
              with:
                source: "README.md"
                target: "pyfigure98/README.md"
            
            - name: Create Release
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: pyfigure98
                  asset_name: pyfigure98-$tag
                  release_name: Python-graphs-${{ github.ref_name }}"
                  tag: ${{ github.ref }}
                  overwrite: true
                  body: ${{steps.github_release.outputs.changelog}}
