name: Publish

on:
    push:
        tags:
            - 'v*.*.*'
jobs:
    release:
        name: Create new release
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Move README & compress the package
              run: |
                  cp README.md pyfigure98/README.md 
                  cd pyfigure98 && zip -r ../pyfigure98.zip .
                  cd ..

            - name: Build Changelog
              id: github_release
              uses: mikepenz/release-changelog-builder-action@v4
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Create Release
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: pyfigure98.zip
                  asset_name: pyfigure98-$tag.zip
                  release_name: pyfigure98-${{ github.ref_name }}"
                  tag: ${{ github.ref }}
                  overwrite: true
                  body: ${{steps.github_release.outputs.changelog}}
